$( "#slider" ).slider({
	range: "min",
	min: 0,
    max: 10000,
	slide: function (event, ui) {
        //$("#amount").val(ui.value);
		var val=ui.value,
			pct=ui.value/100,
			money=parseInt($(".choose .choose-foot .money").html());
			
			money=parseInt(money*pct/100);
		$(".choose .choose-foot .slider-pct").html(pct+"%");
		$(".choose .choose-foot .slider-mun").html(money);
    }
});

function news_content(model,e){
	var main_lists_html="";var classify_childs_html="";
	$(".main .classify .classify-list .classify-list-li").not($(e)).removeClass("on");
	$(e).addClass("on");
	$(".main .classify li").removeClass("on");
	var parent=$(e).closest("li");
	parent.addClass("on");
    $(".main .classify-childs").show();
    $(".main .main-content .demo-title2").hide();
    $(".main .main-content .demo-title3").hide();
    $(".main .main-content .demo-title4").show();
	if(model=="1-1"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p>万位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="even">'
            	+'<div class="l-title"><p>千位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="odd">'
            	+'<div class="l-title"><p>百位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="even">'
            	+'<div class="l-title"><p>十位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="odd">'
            	+'<div class="l-title"><p>个位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
            classify_childs_html='<div class="classify-child classify-child1 yellow">当前遗漏</div><div class="classify-child classify-child2 blue">冷热</div>'

	}else if(model=="1-2"){
		$(".main .classify-childs").hide();
        $(".main .main-content .demo-title2").show();
        $(".main .main-content .demo-title4").hide();
        main_lists_html='<div class="l-textarea"><textarea class="textArea" onblur="add_danshi()" onfocus="remove_danshi()">'+danshi+'</textarea></div>';
        main_lists_html+='<div class="l-btns"><div class="l-btn">删除重复项</div><div class="l-btn" onclick="remove_danshi()">清空文本框</div></div>';
	}else if(model=="8-8"){
        $(".main .classify-childs").hide();
        $(".main .main-content .demo-title2").show();
        $(".main .main-content .demo-title3").show();
        $(".main .main-content .demo-title4").hide();
        main_lists_html='<div class="l-textarea"><textarea class="textArea" onblur="add_danshi()" onfocus="remove_danshi()">'+danshi+'</textarea></div>';
        main_lists_html+='<div class="l-btns"><div class="l-btn">删除重复项</div><div class="l-btn" onclick="remove_danshi()">清空文本框</div></div>';
    }else if(model=="1-3"){
		main_lists_html='<li class="even">'
            	+'<div class="l-title"><p></p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
	}else if(model=="1-4"){
		main_lists_html='<li class="even">'
            	+'<div class="l-title"><p>二重号位</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
			+'<li class="even">'
            	+'<div class="l-title"><p>单号位</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
	}else if(model=="2-1"){
		main_lists_html='<li class="even">'
            	+'<div class="l-title"><p>千位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="odd">'
            	+'<div class="l-title"><p>百位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="even">'
            	+'<div class="l-title"><p>十位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="odd">'
            	+'<div class="l-title"><p>个位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
            classify_childs_html='<div class="classify-child classify-child1 yellow">当前遗漏</div><div class="classify-child classify-child2 blue">冷热</div>'

	}else if(model=="2-2"){
		main_lists_html='<li class="even">'
            	+'<div class="l-title"><p>二重号位</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
	}else if(model=="2-3"){
		main_lists_html='<li class="even">'
            	+'<div class="l-title"><p>三重号位</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
			+'<li class="even">'
            	+'<div class="l-title"><p>单号位</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
	}else if(model=="3-1"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p>万位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="even">'
            	+'<div class="l-title"><p>千位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>'
            +'<li class="odd">'
            	+'<div class="l-title"><p>百位</p><p class="l-msg">当前遗漏</p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
                +'</div>'
                +'<div class="l-mun2">'
                	+'<div class="mun" onclick="select_all(this)">全</div>'
					+'<div class="mun" onclick="select_big(this)">大</div>'
					+'<div class="mun" onclick="select_small(this)">小</div>'
					+'<div class="mun" onclick="select_odd(this)">奇</div>'
					+'<div class="mun" onclick="select_even(this)">偶</div>'
					+'<div class="mun" onclick="select_clear(this)">清</div>'
                +'</div>'
            +'</li>';
            classify_childs_html='<div class="classify-child classify-child1 yellow">当前遗漏</div><div class="classify-child classify-child2 blue">冷热</div>'

	}else if(model=="3-2"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p></p></div>'
                +'<div class="l-mun">'
                	+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">12</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">13</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">14</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">15</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">16</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">17</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">18</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">19</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">20</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">21</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">22</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">23</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">24</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">25</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">26</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">27</div>'
                +'</div>'
            +'</li>';
	}else if(model=="3-3"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p></p></div>'
                +'<div class="l-mun">'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">12</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">13</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">14</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">15</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">16</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">17</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">18</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">19</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">20</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">21</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">22</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">23</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">24</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">25</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">26</div>'
                +'</div>'
            +'</li>';
	}else if(model=="4-1"){
		main_lists_html='<li class="odd">'
			+'<div class="l-title"><p>百位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>'
		+'<li class="even">'
			+'<div class="l-title"><p>十位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>'
		+'<li class="odd">'
			+'<div class="l-title"><p>个位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>';
		classify_childs_html='<div class="classify-child classify-child1 yellow">当前遗漏</div><div class="classify-child classify-child2 blue">冷热</div>';
	}else if(model=="5-1"){
		main_lists_html='<li class="odd">'
			+'<div class="l-title"><p>万位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>'
		+'<li class="even">'
			+'<div class="l-title"><p>千位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>';
		classify_childs_html='<div class="classify-child classify-child1 yellow">当前遗漏</div><div class="classify-child classify-child2 blue">冷热</div>';
	}else if(model=="5-2"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p></p></div>'
                +'<div class="l-mun">'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">12</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">13</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">14</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">15</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">16</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">17</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">18</div>'
                +'</div>'
            +'</li>';
	}else if(model=="5-3"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p></p></div>'
                +'<div class="l-mun">'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">1</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">2</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">3</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">4</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">5</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">6</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">7</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">8</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">9</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">10</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">11</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">12</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">13</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">14</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">15</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">16</div>'
					+'<div class="mun" onclick="$(this).toggleClass(\'on\')">17</div>'
                +'</div>'
            +'</li>';
	}else if(model=="6-1"){
		main_lists_html='<li class="odd">'
			+'<div class="l-title"><p>十位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>'
		+'<li class="even">'
			+'<div class="l-title"><p>个位</p><p class="l-msg">当前遗漏</p></div>'
			+'<div class="l-mun">'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">0<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">1<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">2<p class="l-msg">12</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">3<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">4<p class="l-msg red">14</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">5<p class="l-msg red">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">6<p class="l-msg">7</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">7<p class="l-msg">0</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">8<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">9<p class="l-msg">8</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">10<p class="l-msg">13</p></div>'
				+'<div class="mun" onclick="$(this).toggleClass(\'on\')">11<p class="l-msg">2</p></div>'
			+'</div>'
			+'<div class="l-mun2">'
				+'<div class="mun" onclick="select_all(this)">全</div>'
				+'<div class="mun" onclick="select_big(this)">大</div>'
				+'<div class="mun" onclick="select_small(this)">小</div>'
				+'<div class="mun" onclick="select_odd(this)">奇</div>'
				+'<div class="mun" onclick="select_even(this)">偶</div>'
				+'<div class="mun" onclick="select_clear(this)">清</div>'
			+'</div>'
		+'</li>';
		classify_childs_html='<div class="classify-child classify-child1 yellow">当前遗漏</div><div class="classify-child classify-child2 blue">冷热</div>';
	}else if(model=="7-1"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p>万位</p></div>'
                +'<div class="l-mun">'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">大</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">小</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">单</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">双</div>'
                +'</div>'
            +'</li>'
			+'<li class="even">'
            	+'<div class="l-title"><p>千位</p></div>'
                +'<div class="l-mun">'
                     +'<div class="mun" onclick="$(this).toggleClass(\'on\')">大</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">小</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">单</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">双</div>'
                +'</div>'
            +'</li>';
	}else if(model=="7-2"){
		main_lists_html='<li class="odd">'
            	+'<div class="l-title"><p>十位</p></div>'
                +'<div class="l-mun">'
                     +'<div class="mun" onclick="$(this).toggleClass(\'on\')">大</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">小</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">单</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">双</div>'
                +'</div>'
            +'</li>'
			+'<li class="even">'
            	+'<div class="l-title"><p>个位</p></div>'
                +'<div class="l-mun">'
                     +'<div class="mun" onclick="$(this).toggleClass(\'on\')">大</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">小</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">单</div>'
                    +'<div class="mun" onclick="$(this).toggleClass(\'on\')">双</div>'
                +'</div>'
            +'</li>';
	}
	$(".main .classify .classify-childs").html(classify_childs_html);
	$(".main .lists").html(main_lists_html);
	$(".main .main-content .main-title .title").html($(e).html());
	
}